---
- name: Make Tenant ATX-Ansible1
  hosts: apic1
  connection: local
#  gather_facts:  false
#  user: damcfarl



  vars_files:
    - external_varsATX.yml

  tasks:
    - name:  Creating Tenant
      aci_tenant:
        tenant:  dm_ansible_T88
        description: "ATX-Ansible1 Tenant"
        host:  "{{ host }}"
        username: "{{ user }}"
        password: "{{ aci_password }}"
        validate_certs: "{{ aci_validate_certs  }}"
        state: present


# Modified by damcfarl
#
# Usage:  ansible-playbook PB-UserCred-CreateJustTenant.yml -i SJC-Inventory-file  -vvv
#
#  docs.ansible.com is essential to make sure you got the modules right
# variables are defined in external_varsATX.yml
